package org;
// Generated by Selenium IDE

import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.JavascriptExecutor;

import java.util.*;

public class VerifyTest {

    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    // Setup browser before each test
    @Before
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    // Close browser after test
    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void verify() {

        // 1. LOGIN (VALID USER)
        driver.get("https://www.saucedemo.com/");
        driver.findElement(By.cssSelector("*[data-test=\"username\"]")).sendKeys("standard_user");
        driver.findElement(By.cssSelector("*[data-test=\"password\"]")).sendKeys("secret_sauce");
        driver.findElement(By.cssSelector("*[data-test=\"login-button\"]")).click();

        // Verify login success → cart icon visible
        {
            List<WebElement> elements = driver.findElements(By.cssSelector("*[data-test=\"shopping-cart-link\"]"));
            assert(elements.size() > 0);
        }

        // Verify menu button exists
        {
            List<WebElement> elements = driver.findElements(By.id("react-burger-menu-btn"));
            assert(elements.size() > 0);
        }

        // 2. ADD ITEM TO CART
        driver.findElement(By.cssSelector("*[data-test=\"add-to-cart-sauce-labs-backpack\"]")).click();

        // Verify item added (Remove button appears)
        {
            List<WebElement> elements = driver.findElements(By.cssSelector("*[data-test=\"remove-sauce-labs-backpack\"]"));
            assert(elements.size() > 0);
        }

        driver.findElement(By.cssSelector("*[data-test=\"shopping-cart-link\"]")).click();

        // Verify item exists in cart
        {
            List<WebElement> elements = driver.findElements(By.cssSelector("*[data-test=\"inventory-item-name\"]"));
            assert(elements.size() > 0);
        }

        // Verify checkout button exists
        {
            List<WebElement> elements = driver.findElements(By.cssSelector("*[data-test=\"checkout\"]"));
            assert(elements.size() > 0);
        }

        // 3. CHECKOUT (INVALID INPUT)
        driver.findElement(By.cssSelector("*[data-test=\"checkout\"]")).click();

        // Enter invalid first name (blank)
        driver.findElement(By.cssSelector("*[data-test=\"firstName\"]")).click();
        driver.findElement(By.cssSelector("*[data-test=\"firstName\"]")).sendKeys(" ");

        driver.findElement(By.cssSelector("*[data-test=\"continue\"]")).click();

        // Verify error message appears
        {
            List<WebElement> elements = driver.findElements(By.cssSelector("*[data-test=\"error\"]"));
            assert(elements.size() > 0);
        }
        driver.findElement(By.cssSelector("*[data-test=\"firstName\"]")).sendKeys("a");
        driver.findElement(By.cssSelector("*[data-test=\"lastName\"]")).sendKeys("a");
        driver.findElement(By.cssSelector("*[data-test=\"postalCode\"]")).sendKeys("a");

        driver.findElement(By.cssSelector("*[data-test=\"continue\"]")).click();

        // Verify checkout overview page
        {
            List<WebElement> elements = driver.findElements(By.cssSelector("*[data-test=\"title\"]"));
            assert(elements.size() > 0);
        }

        // Finish order
        driver.findElement(By.cssSelector("*[data-test=\"finish\"]")).click();

        // Verify order completion
        {
            List<WebElement> elements = driver.findElements(By.cssSelector("*[data-test=\"complete-header\"]"));
            assert(elements.size() > 0);
        }

        // 4. LOGOUT
        driver.findElement(By.cssSelector("*[data-test=\"back-to-products\"]")).click();
        driver.findElement(By.id("react-burger-menu-btn")).click();
        driver.findElement(By.cssSelector("*[data-test=\"logout-sidebar-link\"]")).click();

        // Verify back to login page
        {
            List<WebElement> elements = driver.findElements(By.cssSelector("*[data-test=\"login-button\"]"));
            assert(elements.size() > 0);
        }

        // 5. LOGIN (INVALID USER)
        driver.findElement(By.cssSelector("*[data-test=\"username\"]")).sendKeys("aaa");
        driver.findElement(By.cssSelector("*[data-test=\"password\"]")).sendKeys("aaa");
        driver.findElement(By.cssSelector("*[data-test=\"login-button\"]")).click();

        // Verify error message displayed
        {
            List<WebElement> elements = driver.findElements(By.cssSelector("*[data-test=\"error\"]"));
            assert(elements.size() > 0);
        }
    }
}